
spring:
  datasource: #?????
    url: jdbc:mysql://localhost:3306/library-management?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: springboot-jwt
server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml #??????mapper.xml??

config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: token